---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: gcr.io/tas-ppe/source_insight_tooling/osspi-runner
    tag: test
    username: _json_key
    password: ((gcr_service_account))

inputs:
  - name: docs-platform-automation
  - name: image
    optional: true
params:
  IMAGE:
  TAG: latest
  TAR_PATH:
  API_KEY:
  OSM_ENVIRONMENT: beta
  OSSTP_LOAD_DRY_RUN:
  ENDPOINT:
  USERNAME:
  PRODUCT:
  VERSION:
  OSSPI_IGNORE_RULES:
  APPEND:
  CT_TRACKER_OS: ubuntu
run:
  path: docs-platform-automation/ci/tasks/run-osspi-docker/task.sh
