platform: linux
image_resource:
  type: registry-image
  source:
    repository: concourse/docker-image-resource
inputs:
- name: platform-automation-image
- name: platform-automation
- name: version
- name: docs-platform-automation
outputs:
- name: bumped-platform-automation-image
- name: image-receipt
run:
  path: bash
  args:
  - -c
  - |
    #!/bin/bash
    set -eu

    # shellcheck disable=SC1091
    source /opt/resource/common.sh
    start_docker "5" "5" "" ""

    image_name="internalpcfplatformautomation/platform-automation:packages"
    destination="$PWD/bumped-platform-automation-image"

    docker import platform-automation-image/*.tgz "$image_name"
    docker build -t "$image_name" -f docs-platform-automation/ci/dockerfiles/Dockerfile.python-mitigation platform-automation/
    docker run \
      --rm \
      "$image_name" \
      dpkg -l > image-receipt/image-receipt-"$(cat version/version)"

    # https://github.com/concourse/docker-image-resource/blob/2d1bbe884942aaa8dabd7a762ea0dc431c572a27/assets/in#L80
    docker run \
      --cidfile=/tmp/container.cid \
      -v /opt/resource/print-metadata:/tmp/print-metadata \
      --entrypoint /tmp/print-metadata  \
      "$image_name" > "${destination}/metadata.json"

    # https://github.com/concourse/docker-image-resource/blob/2d1bbe884942aaa8dabd7a762ea0dc431c572a27/assets/in#L86
    docker export "$(cat /tmp/container.cid)" | tar --exclude="dev/*" -xf - -C "${destination}/"
    docker rm "$(cat /tmp/container.cid)"
    docker rmi "$image_name"
