---
platform: linux
image_resource:
  type: registry-image
  source:
    repository: harbor-repo.vmware.com/source_insight_tooling/osspi-runner

inputs:
  - name: repo1
  - name: image
    optional: true
params:
  IMAGE:
  TAG: latest
  TAR_PATH:
  API_KEY:
  OSM_ENVIRONMENT: beta
  OSSTP_LOAD_DRY_RUN:
  ENDPOINT:
  USERNAME:
  PRODUCT:
  VERSION:
  OSSPI_IGNORE_RULES:
  APPEND:
  CT_TRACKER_OS: ubuntu
run:
  path: repo1/ci/tasks/run-osspi-docker.sh
